name: first
on:
  push:

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run:  date
  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - name: step1
        run:  date
  macos:
    name: macos
    runs-on: macos-latest
    steps:
      - name: step1
        run:  date
  depends:
    needs:
      [ubuntu, windows, macos]
    name: depends
    runs-on: windows-latest
    steps:
      - name: step1
        run:  date

