name: first
on:
  push:

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run:  date
  job2:
    name: First job
    runs-on: windows-latest
    steps:
      - name: step1
        run:  date
  job3:
    name: First job
    runs-on: macos-latest
    steps:
      - name: step1
        run:  date
  job4:
    needs:
      [job1, job2, job3]
    name: First job
    runs-on: windows-latest
    steps:
      - name: step1
        run:  date

