name: hello
on:
  push:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: list files
        run: |
            ls -la

      - name: deploy python 
        run: |
         python ./hello.py