name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: Configure Azure Credentials
    - uses: actions/checkout@v1
    - uses: azure/login@v2
      with:  
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: List storage accounts
      run: az storage account list
